### ISSUE TITLE
Nightly builds wasn't triggered as expected.

### ISSUE THREAD

**Issue by sophia-guo** [eclipse-openj9/build-openj9#17]
Nightly builds wasn't triggered as expected from Jan 27th. Could the usage limits be reached?

**Comment by smlambert** [comment]
Hmm, I do not think it can be a usage limit, as I am able to successfully [rerun the build](https://github.com/eclipse/build-openj9/actions/runs/522067124) from 6 days ago (and believe I would have received an error message on usage in the case of using up the minutes).

**Comment by sophia-guo** [comment]
Thanks @smlambert ! That's interesting. There is no any extra error message and there is nothing updated in the repo back to 6 days ago

**Comment by smlambert** [comment]
I did not see that workflow is disabled banner, but I am not an admin of this repo like I am at Adopt build-jdk (presumably Eclipse Foundation infra are).  I have noted that when I look at the status of the workflow, it shows the option to disable the workflow (which I interpret as the workflow is currently enabled, which may have happened once I tried to rerun the old run)

<img width="1037" alt="Screen Shot 2021-02-04 at 2 40 18 PM" src="https://user-images.githubusercontent.com/2836948/106946439-16c69380-66f7-11eb-8e96-5e6429830e6c.png">

If I did just trigger it to re-enable itself through rerunning an old run, I suspect it will begin running again tonight.  If it does not run again tonight, we may have to make a request to EF infra to click on a button for us.

**Comment by sophia-guo** [comment]
It didn't run as expected last night. So we might need EF infra's help.

**Comment by sophia-guo** [comment]
[build-jdk](https://github.com/AdoptOpenJDK/build-jdk/issues/20) has same issue and @smlambert re-enabled. Now build-jdk works.

**Comment by sophia-guo** [comment]
Looks good. Close it.
